import React, {useState} from 'react';
async function getForecast(postcode: string): Promise<string> {
  // very basic testing string, you'll likely return a list of strings or JSON objects instead!
  const postcodeString = (postcode === "") ? "" : ` - given postcode is ${postcode}`;
  return "Some cool forecast HTML generated by TypeScript" + postcodeString;
}
function App(): React.ReactElement {
  const [postcode, setPostcode] = useState<string>("");
  const [tableData, setTableData] = useState<string>("");
  async function formHandler(event: React.FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault(); // to stop the form refreshing the page when it submits
    const data = await getForecast(postcode);
    setTableData(data);
  }
  function updatePostcode(data: React.ChangeEvent<HTMLInputElement>): void {
    setPostcode(data.target.value)
  }
  return <>
    <h1> Met Office Weather </h1>
    <form action="" onSubmit={formHandler}>
      <label htmlFor="postcodeInput"> Postcode: </label>
      <input type="text" id="postcodeInput" onChange={updatePostcode}/>
      <input type="submit" value="Submit"/>
    </form>
    {JSON.stringify(tableData, null, 4) /* this will just render the string - try creating a table 'dynamically'! */}
  </>;
}
export default App;